### ISSUE TITLE
how to install auto2?

### ISSUE THREAD

**Issue by medovina** [bzhan/auto2#4]
I'd like to try to use auto2 in some of my own Isabelle proofs.  So I'd like to install it, i.e. make it available as an Isabelle tactic.

Unfortunately I don't know how to do this.  As one attempt, I created a file ~/.isabelle/ROOTS containing this text:

```
/home/adam/src/auto2
```

That the the directory where I cloned the auto2 repository.  I hoped that would make auto2 available as a session.  Then at the top of my theory file I typed

```
theory arith
imports Main "Auto2_HOL.Auto2_Main"
begin
```

However that failed - Isabelle reported

```
Bad theory import "Auto2_HOL.Auto2_Main"
```

I'm not sure if I'm using the right approach at all.

It would be helpful if your documentation (e.g. the README) explained how a user can install and use your tool - thanks.

**Comment by bzhan** [comment]
As suggested on the Isabelle mailing list, you may wish to use the version of auto2 in AFP.

The version on github was updated only to Isabelle2020. I just incorporated updates from AFP to move it to Isabelle2021-1. I then tried what you did and it seems to work. Does the problem still persist for you?

**Comment by medovina** [comment]
Hi Bohua - thanks for your reply.  I was able to use the version in AFP successfully.  Also, I realized my previous mistake: I had created a file `~/.isabelle/ROOTS`, but actually it needed to be `~/.isabelle/isabelle2021-1/ROOTS` since that's where the release I was using expected to find it.

In any case, I'm now able to use auto2.  Thanks!
